AWSTemplateFormatVersion: 2010-09-09
Description: >-
  Create ECR Repository, Code build
Parameters:
  GitHubRepo:
    Type: String
    Description: "GitHubRepo"
    Default: sknampally/awsms-poc-springboot
  GitHubBranch:
    Type: String
    Description: "GitHubBranch"
    AllowedValues:
      - master
    Default: master
  GitHubToken:
    Type: String
    NoEcho: true
  GitHubUser:
    Type: String
  TemplateBucket:
    Type: String
Resources:
  Repository:
    Type: AWS::ECR::Repository
    DeletionPolicy: Retain
    Properties:
      RepositoryName: awsms-poc-springboot
  ArtifactBucket:
    Type: AWS::S3::Bucket
    DeletionPolicy: Retain
  CodeBuildServiceRole:
    Type: AWS::IAM::Role
    Properties:
      Path: /
      ManagedPolicyArns:
          - "arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryFullAccess"
          - "arn:aws:iam::aws:policy/AdministratorAccess"
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Principal:
              Service: codebuild.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: root
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Resource: "*"
                Effect: Allow
                Action:
                  - logs:CreateLogGroup
                  - logs:CreateLogStream
                  - logs:PutLogEvents
                  - ecr:GetAuthorizationToken
              - Resource: !Sub arn:aws:s3:::${ArtifactBucket}/*
                Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:GetObjectVersion
                  - s3:ListObjects
                  - s3:ListBucket
              - Resource: "*"
                Effect: Allow
                Action:
                  - "ecr:GetAuthorizationToken"
                  - "ecr:BatchCheckLayerAvailability"
                  - "ecr:GetDownloadUrlForLayer"
                  - "ecr:GetRepositoryPolicy"
                  - "ecr:DescribeRepositories"
                  - "ecr:ListImages"
                  - "ecr:DescribeImages"
                  - "ecr:BatchGetImage"
                  - "ecr:GetLifecyclePolicy"
                  - "ecr:GetLifecyclePolicyPreview"
                  - "ecr:ListTagsForResource"
                  - "ecr:DescribeImageScanFindings"
                  - "ecr:InitiateLayerUpload"
                  - "ecr:UploadLayerPart"
                  - "ecr:CompleteLayerUpload"
                  - "ecr:PutImage"
              - Resource: "*"
                Effect: Allow
                Action:
                   - "ecr:*"
                   - "cloudtrail:LookupEvents"
                Resource: arn:aws:logs:us-west-2:160357565307:log-group:/aws/codebuild/Sample-CodeBuildProject
  CodeBuildProject:
    Type: AWS::CodeBuild::Project
    Properties:
      Name: awsms-code-build
      ServiceRole: !GetAtt CodeBuildServiceRole.Arn
      Artifacts:
        Type: no_artifacts
      Environment:
        Type: LINUX_CONTAINER
        ComputeType: BUILD_GENERAL1_SMALL
        Image: aws/codebuild/standard:2.0
        PrivilegedMode: true
      Source:
        Auth:
          Type: OAUTH
        Location: https://github.com/sknampally/awsms-poc-springboot.git
        Type: GITHUB
      Triggers:
        Webhook: false
        #FilterGroups:
        #- - Type: EVENT
            #Pattern: PUSH
          #- Type: HEAD_REF
            #Pattern: ^refs/heads/.*
          #- Type: FILE_PATH
            #Pattern: READ_ME
            #ExcludeMatchedPattern: true
      TimeoutInMinutes: 10
Outputs:
  Repository:
    Description: The name of the ECR Repository
    Value: !Ref Repository
    Export:
      Name: !Sub 'RepositoryName'
  BuildProject:
    Description: The name of the Code build
    Value: !Ref CodeBuildProject
    Export:
      Name: 'CodeBuildProject'
